flowable:
  databaseSchemaUpdate : true #create-drop create false
  cmmn.enabled : true
  dmn.enabled : true
  form.enabled : true
  databaseSchema : liansen_flow

logging:
  name: flow-service

---

#生产环境
spring.profiles: service-pro


---

#开发环境
spring.profiles: service-dev

server:
  port : 8084

spring:
  profiles:
    include: service-pro
#  datasource:
#    url : jdbc:mysql://123.56.2.28:3306/liansen_flow?useUnicode=true&characterEncoding=UTF-8
#    username : root
#    password: Service80!!
  datasource:
    url : jdbc:mysql://localhost:3306/liansen_flow?useUnicode=true&characterEncoding=UTF-8
    username : root
    password: root

#熔断器超时
#避免第一次调用失败
hystrix:
  threadpool:
    default:
      coreSize: 500
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 80000
# 正式环境
#php:
#  url: 123.56.2.28:2738
php:
  url: 192.168.249.211:66