logging:
  name: identity-service
     
     
---

#生产环境
spring.profiles: service-pro
  
  
---

#开发环境
spring.profiles: service-dev
  
server:
  port : 8082

spring:
  profiles:
    include: service-pro
  datasource:
    url : jdbc:mysql://123.56.2.28:3306/ksh?useUnicode=true&characterEncoding=UTF-8
    username : root
    password: Service80!!
  redis:
    host: 192.168.249.211
    port: 6379
    password:
    maxTotal: 30

redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: ${REDIS_HOST:localhost}
    port:  ${REDIS_PORT:6379}
    password:
    timeout: 2000