logging:
  name: identity-service
     
     
---

#生产环境
spring.profiles: service-pro
  
  
---

#开发环境
spring.profiles: service-dev
  
server:
  port : 8082

spring:
  profiles:
    include: service-pro
  datasource:
    url : jdbc:mysql://123.56.2.28:3306/ksh?useUnicode=true&characterEncoding=UTF-8
    username : root
    password: Service80!!
  